coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: auto
        threshold: 5%
        if_not_found: success

ignore:
  - "**/mocks/"
  - "cmd/"
  - "docs/"
  - "pkg/"
  - "vendor/"
  - "proto/"
  - "internal/server"
